export const UPDATE_DATA_USER = 'update_data_user'
export const UPDATE_DATA_ROLES = 'update_data_roles'
export const UPDATE_DATA_CURRENT_USER_ROLE = 'update_data_current_user_role'
export const UPDATE_CURRENT_VISIBLE = 'update_current_visible'
export const UPDATE_PRESENT_USER = 'update_present_user'
export const UPDATE_PRESENT_USERNAME = 'update_present_username'
